<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsersSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        // Hash passwords for security
        $clientPassword = password_hash('Client123!', PASSWORD_DEFAULT);
        $adminPassword = password_hash('Admin123!', PASSWORD_DEFAULT);
        $organizerPassword = password_hash('Organizer123!', PASSWORD_DEFAULT);

        $users = [
            // Admin User
            [
                'first_name' => 'Admin',
                'middle_name' => 'System',
                'last_name' => 'BeatSync',
                'email' => 'admin@beatsync.com',
                'password_hash' => $adminPassword,
                'phone' => '+639171234567',
                'date_of_birth' => '1990-01-15',
                'gender' => 'male',
                'profile_image' => null,
                'bio' => 'BeatSync platform administrator',
                'user_type' => 'admin',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['House', 'Techno', 'Trance']),
                'location_city' => 'Manila',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => $now,
                'last_login_ip' => '127.0.0.1',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 1,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Event Organizer 1
            [
                'first_name' => 'Maria',
                'middle_name' => 'Santos',
                'last_name' => 'Cruz',
                'email' => 'maria.cruz@eventpro.ph',
                'password_hash' => $organizerPassword,
                'phone' => '+639181234568',
                'date_of_birth' => '1988-05-20',
                'gender' => 'female',
                'profile_image' => null,
                'bio' => 'Professional EDM event organizer specializing in large-scale music festivals',
                'user_type' => 'organizer',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Progressive House', 'Big Room', 'Future Bass']),
                'location_city' => 'BGC, Taguig',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => $now,
                'last_login_ip' => '192.168.1.10',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Event Organizer 2
            [
                'first_name' => 'Carlos',
                'middle_name' => 'David',
                'last_name' => 'Reyes',
                'email' => 'carlos.reyes@edmmanila.com',
                'password_hash' => $organizerPassword,
                'phone' => '+639191234569',
                'date_of_birth' => '1985-11-08',
                'gender' => 'male',
                'profile_image' => null,
                'bio' => 'Passionate about bringing world-class DJs to the Philippines',
                'user_type' => 'organizer',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Techno', 'Deep House', 'Minimal']),
                'location_city' => 'Makati',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-2 days')),
                'last_login_ip' => '192.168.1.20',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 1
            [
                'first_name' => 'Juan',
                'middle_name' => 'Pedro',
                'last_name' => 'Dela Cruz',
                'email' => 'juan.delacruz@gmail.com',
                'password_hash' => $clientPassword,
                'phone' => '+639201234570',
                'date_of_birth' => '1995-03-12',
                'gender' => 'male',
                'profile_image' => null,
                'bio' => 'EDM enthusiast, love attending festivals and concerts!',
                'user_type' => 'client',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Dubstep', 'Trap', 'Bass House']),
                'location_city' => 'Quezon City',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-1 hour')),
                'last_login_ip' => '192.168.1.30',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 2
            [
                'first_name' => 'Sofia',
                'middle_name' => 'Isabel',
                'last_name' => 'Garcia',
                'email' => 'sofia.garcia@yahoo.com',
                'password_hash' => $clientPassword,
                'phone' => '+639211234571',
                'date_of_birth' => '1998-07-25',
                'gender' => 'female',
                'profile_image' => null,
                'bio' => 'Living for the drop! Always ready for the next rave.',
                'user_type' => 'client',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Trance', 'Progressive House', 'Melodic Techno']),
                'location_city' => 'Pasig',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-3 hours')),
                'last_login_ip' => '192.168.1.40',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 3
            [
                'first_name' => 'Miguel',
                'middle_name' => 'Antonio',
                'last_name' => 'Santos',
                'email' => 'miguel.santos@outlook.com',
                'password_hash' => $clientPassword,
                'phone' => '+639221234572',
                'date_of_birth' => '1992-09-30',
                'gender' => 'male',
                'profile_image' => null,
                'bio' => 'Festival junkie, been to Ultra, Tomorrowland, and counting!',
                'user_type' => 'client',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Big Room', 'Electro House', 'Future Bass', 'Hardstyle']),
                'location_city' => 'BGC, Taguig',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
                'last_login_ip' => '192.168.1.50',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 4
            [
                'first_name' => 'Gabriela',
                'middle_name' => 'Marie',
                'last_name' => 'Torres',
                'email' => 'gabi.torres@gmail.com',
                'password_hash' => $clientPassword,
                'phone' => '+639231234573',
                'date_of_birth' => '1996-12-18',
                'gender' => 'female',
                'profile_image' => null,
                'bio' => 'Music is life! Techno beats and good vibes.',
                'user_type' => 'client',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Techno', 'Tech House', 'Acid House']),
                'location_city' => 'Makati',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-5 hours')),
                'last_login_ip' => '192.168.1.60',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 5 (Unverified)
            [
                'first_name' => 'Andre',
                'middle_name' => 'Luis',
                'last_name' => 'Mendoza',
                'email' => 'andre.mendoza@proton.me',
                'password_hash' => $clientPassword,
                'phone' => '+639241234574',
                'date_of_birth' => '1999-04-05',
                'gender' => 'male',
                'profile_image' => null,
                'bio' => 'New to the scene, ready to experience EDM culture!',
                'user_type' => 'client',
                'account_status' => 'pending',
                'email_verified' => 0,
                'email_verification_token' => bin2hex(random_bytes(32)),
                'email_verified_at' => null,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['House', 'Dance Pop']),
                'location_city' => 'Manila',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => null,
                'last_login_ip' => null,
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 6 (Inactive)
            [
                'first_name' => 'Patricia',
                'middle_name' => 'Nicole',
                'last_name' => 'Ramos',
                'email' => 'patricia.ramos@gmail.com',
                'password_hash' => $clientPassword,
                'phone' => null,
                'date_of_birth' => '1994-08-22',
                'gender' => 'female',
                'profile_image' => null,
                'bio' => null,
                'user_type' => 'client',
                'account_status' => 'inactive',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => date('Y-m-d H:i:s', strtotime('-6 months')),
                'newsletter_subscribed' => 0,
                'favorite_genres' => json_encode(['Chill House', 'Tropical House']),
                'location_city' => 'Cebu City',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-180 days')),
                'last_login_ip' => '192.168.1.70',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 year')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('-6 months')),
                'deleted_at' => null,
            ],

            // Client User 7
            [
                'first_name' => 'Rafael',
                'middle_name' => 'Jose',
                'last_name' => 'Villanueva',
                'email' => 'rafael.villanueva@yahoo.com',
                'password_hash' => $clientPassword,
                'phone' => '+639251234575',
                'date_of_birth' => '1997-02-14',
                'gender' => 'male',
                'profile_image' => null,
                'bio' => 'Bass music fanatic! Catch me at every dubstep show.',
                'user_type' => 'client',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['Dubstep', 'Riddim', 'Drum and Bass', 'Brostep']),
                'location_city' => 'Parañaque',
                'location_country' => 'Philippines',
                'timezone' => 'Asia/Manila',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-30 minutes')),
                'last_login_ip' => '192.168.1.80',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],

            // Client User 8 (International)
            [
                'first_name' => 'Emma',
                'middle_name' => null,
                'last_name' => 'Johnson',
                'email' => 'emma.johnson@gmail.com',
                'password_hash' => $clientPassword,
                'phone' => '+1234567890',
                'date_of_birth' => '1993-06-10',
                'gender' => 'female',
                'profile_image' => null,
                'bio' => 'Traveling DJ enthusiast, exploring EDM scenes worldwide!',
                'user_type' => 'client',
                'account_status' => 'active',
                'email_verified' => 1,
                'email_verification_token' => null,
                'email_verified_at' => $now,
                'newsletter_subscribed' => 1,
                'favorite_genres' => json_encode(['House', 'Tech House', 'Deep House', 'Garage']),
                'location_city' => 'Los Angeles',
                'location_country' => 'USA',
                'timezone' => 'America/Los_Angeles',
                'last_login_at' => date('Y-m-d H:i:s', strtotime('-2 hours')),
                'last_login_ip' => '203.0.113.45',
                'password_reset_token' => null,
                'password_reset_expires_at' => null,
                'remember_token' => null,
                'two_factor_enabled' => 1,
                'two_factor_secret' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ];

        // Insert all users
        $this->db->table('users')->insertBatch($users);

        // Display success message
        echo "\n✅ Successfully seeded " . count($users) . " users!\n";
        echo "📧 Admin: admin@beatsync.com (Password: Admin123!)\n";
        echo "🎫 Organizers: maria.cruz@eventpro.ph, carlos.reyes@edmmanila.com (Password: Organizer123!)\n";
        echo "🎵 Clients: Use Client123! for all client accounts\n\n";
    }
}
